### ISSUE TITLE
Guess we will never see HSL() support in node

### ISSUE THREAD

**Issue by BassOfBass** [meduzen/true-hsl.scss#1]
https://github.com/sass/sass/issues/2564#issuecomment-716888385
https://sass-lang.com/blog/libsass-is-deprecated

**Comment by meduzen** [comment]
Hi @BassOfBass. I don’t understand why you’re posting this issue. If you which to elaborate, I’d be happy to read.

**Comment by BassOfBass** [comment]
@meduzen 
Just saying your fix will forever be in limbo state, as the main problem with `hsl()` in SASS was related to Node.

**Comment by meduzen** [comment]
The `hsl` _problem_ exists in projects using the old SASS spec (through `node-sass` or whatever else), so there’s of course no reason to use this package in projects using the new spec.

I’m closing this issue; comments remain open.
